### ISSUE TITLE
Support loading iBridgeBaron screenshots

### ISSUE THREAD

**Issue by danvk** [danvk/dds.js#18]
This would be a really convenient way to load hands on phones.

I'm not sure what File Upload buttons do on mobile. Can they be made to bring up the photo selector?

cc @mshron

**Comment by danvk** [comment]
it's possible: http://code.hootsuite.com/html5/

**Comment by danvk** [comment]
Here's a sample screenshot. I think a hacky approach would work well:
- Extract rectangles from hard-coded coordinates for each card.
- Match the suit and number/symbol against each possibility.

You can almost get away with looking for a red or black pixel to determine suits. But that doesn't quite work: what if you have a two-suited hand with spades and hearts? How do you tell that from diamonds and clubs?

![img_1362](https://cloud.githubusercontent.com/assets/98301/11148054/58a86cfc-89e8-11e5-9ce2-d2c2b9015570.PNG)

**Comment by mshron** [comment]
You resize it (bilinear interpolation is fine) to be a standard size and
make it black and white. Then you do some kind of window on the array of
pixels to turn it into arrays of blocks of suit pixels and arrays of blocks
of number pixels.

Then you can probably do a simple NN lookup against each shape and
alphanumeric and get perfect results, as long as they don't change their
font.

**Comment by danvk** [comment]
That sounds about right. The font may have changed from iOS 8 to iOS 9, but if we're both running iOS 9 then I don't think we care.

For bonus points, we could write a function that takes a font name and generates canonical suit + letter images for comparison.

**Comment by danvk** [comment]
At first glance, it might seem like you need to compute ~52x52 distances between card images to find the hand for the screenshot. But it's not so bad. We know in advance that the cards are sorted, so we shouldn't ever have to do more than 52 comparisons per player. And once a card is matched, it can't appear in anyone else's hand. So we shouldn't have to do more than 52 + 39 + 26 + 13 = 130 image comparisons.

**Comment by danvk** [comment]
Closed via 29ae7643187ca35ec000bdb4e68cc6d5c5316246
